'use strict';
const $=id=>document.getElementById(id);
// The private setup shortcut carries ownership proof in the fragment. Remove
// it before any requests; never store it in browser storage or send it as a URL.
let setupCode='';
if(location.hash){const params=new URLSearchParams(location.hash.slice(1));const token=params.get('setup');if(token&&/^[A-Za-z0-9_-]{43}$/.test(token))setupCode=token;window.history.replaceState(null,'',location.pathname+location.search);}
let pendingSMS=null;
let auth=null,tab='overview',refreshing=false,poll=null,status=null,wifi=null,node=null,caps=null;
const history={cpu:[],memory:[],signal:[]};
const text=v=>v===undefined||v===null||v===''?'—':String(v);
const bytes=v=>{if(v===null||v===undefined||!Number.isFinite(Number(v)))return '—';const n=Number(v);return n<1024?n.toFixed(0)+' B':n<1048576?(n/1024).toFixed(1)+' KiB':n<1073741824?(n/1048576).toFixed(1)+' MiB':(n/1073741824).toFixed(2)+' GiB'};
const percent=v=>v==null?'—':Number(v).toFixed(1)+'%';
const age=v=>{if(v==null)return '—';const n=Math.floor(v);return n>=86400?Math.floor(n/86400)+' 天 '+Math.floor(n%86400/3600)+' 小时':n>=3600?Math.floor(n/3600)+' 小时 '+Math.floor(n%3600/60)+' 分':Math.floor(n/60)+' 分'};
const names={inbound:'收到',outbound:'发出',received:'已接收',sending:'发送中',sent:'已发送',ready:'就绪',missing:'未插 SIM',offline:'离线',unknown:'未知',failed:'失败',registered:'已注册',unregistered:'未注册',searching:'搜网中',denied:'注册被拒绝',roaming:'漫游',paired:'已配对',unpaired:'未配对',PAIRED:'已配对',UNPAIRED:'未配对',CONNECTED:'已连接',CONNECTING:'连接中',PROVISIONING_AP:'配网热点',NO_WIFI_CONFIG:'未配置',FAILED:'连接失败',yes:'是',no:'否',lte:'LTE',umts:'3G',gsm:'2G'};
const label=v=>names[v]||text(v);
const operator=v=>({'CHN-CT':'中国电信','China Telecom':'中国电信','CHN-UNICOM':'中国联通','CHN-CU':'中国联通','China Unicom':'中国联通','CHN-CM':'中国移动','China Mobile':'中国移动'})[v]||text(v);
function notice(message,error=false){if(!auth?.authenticated){$('login-error').textContent=message;$('login-error').hidden=!message||!error;}$('notice').textContent=message;$('notice').classList.toggle('error',error);$('notice').hidden=!message;}
async function request(path,body,method){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),45000);try{const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(auth?.csrf)headers['X-CSRF-Token']=auth.csrf;const res=await fetch(path,{method:method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin',cache:'no-store',signal:controller.signal});const data=await res.json();if(!res.ok){if(res.status===401&&path.startsWith('/admin/api/'))await session();throw new Error(typeof data.error==='string'?data.error:data.error?.message||data.message||'设备请求失败（'+res.status+'）')}return data}finally{clearTimeout(timeout)}}
const api=(path,body,method)=>request('/admin/api/v1/'+path,body,method);
async function busy(button,fn){button.disabled=true;try{await fn()}catch(err){notice(err.name==='AbortError'?'设备响应超时，请确认 USB 或 Wi-Fi 连接。':err.message,true)}finally{button.disabled=false}}
function el(tag,content,className){const e=document.createElement(tag);if(content!==undefined)e.textContent=text(content);if(className)e.className=className;return e}
function row(container,key,value){const r=el('div',undefined,'row');r.append(el('span',key),el('span',value));container.append(r)}
function detail(container,key,value){const d=el('div');d.append(el('small',key),el('b',value));container.append(d)}
function card(title,subtitle,value,details,series){const c=el('article',undefined,'card'),h=el('div',undefined,'card-title');h.append(el('strong',title),el('span',subtitle));c.append(h);c.append(el('div',value,'big'));if(series){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 300 65');svg.setAttribute('aria-label',title+'趋势');svg.classList.add('chart');for(const y of [10,32,55]){const l=document.createElementNS(ns,'line');l.setAttribute('x1','0');l.setAttribute('x2','300');l.setAttribute('y1',y);l.setAttribute('y2',y);svg.append(l)}const p=document.createElementNS(ns,'polyline');p.setAttribute('points',series.map((n,i)=>`${i*300/Math.max(1,series.length-1)},${60-Math.max(0,Math.min(100,n))*.55}`).join(' '));svg.append(p);c.append(svg)}const ds=el('div',undefined,'details');for(const [key,v]of details)detail(ds,key,v);c.append(ds);return c}
function push(key,v){if(v==null)return;history[key].push(Number(v));if(history[key].length>60)history[key].shift()}
function render(){const s=status||{},r=s.resources||{},m=r.metrics||{},sig=s.signal||{},sim=s.sim||{},n=s.network||{},memory=r.memory_total_bytes?100*(1-r.memory_available_bytes/r.memory_total_bytes):null;push('cpu',r.cpu_percent);push('memory',memory);push('signal',sig.known?(sig.bars||0)*20:null);$('sample-time').textContent='采样 '+(r.observed_at?new Date(r.observed_at).toLocaleTimeString():'未上报');$('identity').textContent=[node?.model||auth.model,auth.device_id,operator(n.operator_name||sim.operator_name)].filter(Boolean).join(' · ');const cards=$('cards');cards.replaceChildren();
cards.append(card('CPU 负载',m.cpu_model_name||'本机 CPU',percent(r.cpu_percent),[['CPU 温度',m.cpu_temp_celsius==null?'未上报':Number(m.cpu_temp_celsius).toFixed(1)+' °C'],['核心 / 进程',text(m.cores)+' 核 / '+text(r.process_count)]],history.cpu));
cards.append(card('内存',bytes(r.memory_total_bytes),percent(memory),[['已用',r.memory_total_bytes?bytes(r.memory_total_bytes-r.memory_available_bytes):'—'],['可用',bytes(r.memory_available_bytes)]],history.memory));
cards.append(card('持久存储',m.flash_fs_type||'设备存储',percent(m.flash_used_percent),[['总容量',bytes(m.flash_total_bytes)],['剩余',bytes(m.flash_free_bytes)]]));
cards.append(card('4G 模组',[n.operator_code,label(n.access_technology)].filter(Boolean).join(' · '),label(n.registration),[['RSRP',sig.rsrp==null?'—':sig.rsrp+' dBm'],['SINR',sig.snr==null?'—':sig.snr+' dB']],history.signal));
cards.append(card('SIM 卡',operator(sim.operator_name),label(sim.state),[['手机号',sim.phone_number||'SIM 未提供'],['ICCID',sim.iccid?'••••'+sim.iccid.slice(-4):'—']]));
cards.append(card('无线网络',wifi?.ssid||wifi?.ap_ssid||'Wi-Fi',label(wifi?.state),[['Wi-Fi 地址',wifi?.ipv4||wifi?.ap_address||'—'],['已保存网络',wifi?.saved_ssid||'未配置']]));
cards.append(card('系统运行',auth.device_id,age(r.uptime_seconds),[['软件版本',auth.version],['NAS 配对',label(node?.pairing_state)]]));
cards.append(card('通话与短信','能力来自实际后端',caps?.voice_audio?'音频已就绪':'音频尚未就绪',[['短信能力',caps?.sms?'可用':'不可用'],['IMS / VoLTE',label(caps?.volte)]]));
const p=$('processes');p.replaceChildren();for(const proc of r.processes||[]){const tr=el('tr');tr.append(el('td',proc.pid),el('td',proc.name),el('td',bytes(proc.rss_bytes)));p.append(tr)}if(!p.children.length){const tr=el('tr'),td=el('td','尚未上报');td.colSpan=3;tr.append(td);p.append(tr)}
const ni=$('interfaces');ni.replaceChildren();for(const i of m.interfaces||[])row(ni,i.name,'↓ '+bytes(i.rx_bytes)+' / ↑ '+bytes(i.tx_bytes));if(!ni.children.length)ni.append(el('p','尚未上报','hint'));
const info=$('device-info');info.replaceChildren();for(const [k,v]of [['设备 ID',auth.device_id],['型号',auth.model],['Agent 版本',auth.version],['协议',node?.protocol],['NAS 配对',label(node?.pairing_state)],['当前管理地址',location.origin]])row(info,k,v);
$('wifi-state').textContent=[label(wifi?.state),wifi?.ssid||wifi?.ap_ssid,wifi?.ipv4||wifi?.ap_address].filter(Boolean).join(' · ');}
async function session(){auth=await request('/admin/session');const yes=auth.authenticated;if(!yes){status=wifi=node=caps=pendingSMS=null;for(const id of ['cards','processes','interfaces','device-info','messages'])$(id).replaceChildren();$('logs').textContent='';for(const k of Object.keys(history))history[k]=[];}$('login').hidden=yes;$('workspace').hidden=!yes;$('nav').hidden=!yes;$('logout').hidden=!yes;$('refresh').hidden=!yes;$('title').textContent=yes?'设备管理':'棒子管理';$('identity').textContent=[auth.model,auth.device_id].filter(Boolean).join(' · ');$('footer-id').textContent=auth.device_id;if(auth.configured)setupCode='';$('setup-label').hidden=auth.configured||!!setupCode;$('setup-confirm-label').hidden=auth.configured;$('setup-confirm').required=!auth.configured;$('login-password').minLength=auth.configured?0:12;$('login-password').autocomplete=auth.configured?'current-password':'new-password';$('login-title').textContent=auth.configured?'欢迎回来':'设置管理密码';$('login-help').textContent=auth.configured?'输入本机管理密码，访问设备后台。':(setupCode?'设备已确认，只需设置至少 12 位管理密码并再次输入确认。':'请使用设备专用的「设置棒子管理密码」入口。高级维护也可手动输入设备初始化码。');$('login-submit').textContent=auth.configured?'登录设备':'设置密码并登录';clearTimeout(poll);if(yes)await refresh();}
async function refresh(){if(refreshing||!auth?.authenticated)return;refreshing=true;try{status=await api('status');if(!wifi)wifi=await api('wifi');if(!node)node=await api('node');if(!caps)caps=await api('capabilities');render();$('connection').textContent='设备已连接';}catch(err){notice(err.message,true);$('connection').textContent='连接异常';}finally{refreshing=false;clearTimeout(poll);if(auth?.authenticated)poll=setTimeout(tick,10000)}}
function tick(){if(!auth?.authenticated)return;if(!document.hidden&&tab==='overview')refresh();else poll=setTimeout(tick,10000)}
async function switchTab(next){tab=next;for(const page of document.querySelectorAll('.page'))page.hidden=page.id!==next;for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('selected',b.dataset.tab===next);notice('');try{if(next==='wifi'){wifi=await api('wifi');render()}if(next==='sms')await loadSMS();if(next==='diagnostics')await loadLogs()}catch(err){notice(err.message,true)}}
async function loadSMS(){const data=await api('sms'),list=$('messages');list.replaceChildren();for(const msg of [...(data.messages||[])].reverse()){const c=el('article',undefined,'card'),head=el('div',undefined,'message-head'),left=el('div');left.append(el('strong',msg.peer||'未知号码'),el('small',label(msg.direction)+' · '+(msg.timestamp?new Date(msg.timestamp).toLocaleString():msg.state||'')));const del=el('button','删除','quiet');del.addEventListener('click',()=>busy(del,async()=>{if(confirm('删除棒子上的这条短信？')){await api('sms/'+encodeURIComponent(msg.id),undefined,'DELETE');await loadSMS()}}));head.append(left,del);c.append(head,el('div',msg.text||msg.body||'','message'));list.append(c)}if(!list.children.length)list.append(el('div','棒子上暂时没有短信。','card hint'))}
async function loadLogs(){const data=await api('logs?limit=200');$('logs').textContent=(data.records||[]).map(r=>new Date(r.time).toLocaleTimeString()+'  '+r.level.toUpperCase()+'  '+r.source+'  '+r.message).join('\n')||'暂时没有日志。'}
$('login-form').addEventListener('submit',e=>{e.preventDefault();busy($('login-submit'),async()=>{if(!auth.configured&&!setupCode&&!$('setup-code').value.trim())throw new Error('请在 NAS 的 SIM 节点页点击「打开棒子后台」，进入后直接设置密码。高级维护也可填写设备初始化码。');if(!$('login-password').value)throw new Error('请输入管理密码');if(!auth.configured&&$('login-password').value.length<12)throw new Error('管理密码至少需要 12 位');if(!auth.configured&&$('login-password').value!==$('setup-confirm').value)throw new Error('两次输入的密码不一致');await request('/admin/login',{password:$('login-password').value,setup_code:setupCode||$('setup-code').value});setupCode='';$('login-form').reset();notice('');await session()})});
for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',()=>switchTab(b.dataset.tab));
$('refresh').addEventListener('click',()=>busy($('refresh'),async()=>{wifi=null;node=null;caps=null;await refresh()}));
$('logout').addEventListener('click',()=>busy($('logout'),async()=>{await request('/admin/logout',{});status=wifi=node=caps=null;for(const key of Object.keys(history))history[key]=[];$('messages').replaceChildren();$('logs').textContent='';await session()}));
$('scan').addEventListener('click',()=>busy($('scan'),async()=>{const d=await api('wifi/scan',{}),list=$('networks');list.replaceChildren();for(const n of d.networks||[]){const b=el('button',undefined,'network');b.type='button';b.append(el('strong',n.ssid),el('small',n.security.toUpperCase()+' · '+n.signal_dbm+' dBm'+(n.channel?' · 信道 '+n.channel:'')));b.addEventListener('click',()=>{$('ssid').value=n.ssid;$('security').value=['wpa2','wpa3','open'].includes(n.security)?n.security:'wpa2';$('psk').focus()});list.append(b)}if(!list.children.length)list.append(el('p','暂未发现可见网络。','hint'))}));
$('wifi-form').addEventListener('submit',e=>{e.preventDefault();const b=e.submitter;busy(b,async()=>{const body={ssid:$('ssid').value,security:$('security').value,psk:$('security').value==='open'?'':$('psk').value};$('psk').value='';wifi=await api('wifi/connect',body);render();notice('配置已提交。当前状态：'+label(wifi.state)+(wifi.failure_reason?' · '+wifi.failure_reason:''),wifi.state==='FAILED')})});
$('forget').addEventListener('click',()=>busy($('forget'),async()=>{if(!confirm('忘记当前 Wi-Fi？设备将尝试返回配网热点，USB 管理继续可用。'))return;wifi=await api('wifi/forget',{});render();notice('已忘记保存的无线网络。')}));
$('sms-refresh').addEventListener('click',()=>busy($('sms-refresh'),loadSMS));
$('sms-form').addEventListener('submit',e=>{e.preventDefault();busy(e.submitter,async()=>{if(!confirm('通过当前 SIM 向 '+$('sms-number').value+' 发送这条短信？'))return;const to=$('sms-number').value,body=$('sms-text').value;if(!pendingSMS||pendingSMS.to!==to||pendingSMS.text!==body)pendingSMS={request_id:crypto.randomUUID(),to,text:body};await api('sms/send',pendingSMS);pendingSMS=null;$('sms-text').value='';notice('短信已提交给模组。');await loadSMS()})});
$('logs-refresh').addEventListener('click',()=>busy($('logs-refresh'),loadLogs));
$('download-diag').addEventListener('click',()=>{const a=el('a');a.href='/admin/api/v1/diagnostics/archive';a.download='nassimhub-diagnostics.tar.gz';a.click()});
$('password-form').addEventListener('submit',e=>{e.preventDefault();busy(e.submitter,async()=>{if($('new-password').value!==$('confirm-password').value)throw new Error('两次输入的新密码不一致');const data=await request('/admin/password',{current_password:$('old-password').value,password:$('new-password').value});auth.csrf=data.csrf;$('password-form').reset();notice('管理密码已更新，其他管理会话已退出。')})});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&auth?.authenticated&&tab==='overview')refresh()});
session().catch(e=>notice('无法访问棒子管理服务：'+e.message,true));
