// Command transport-bench measures the handshake and the transports, and
// writes benchmarks/TRANSPORT_BENCHMARK.md.
//
// It is a program rather than a Go benchmark because the output is a document a
// person reads, not a number a machine compares - and because the transport
// grid needs a deterministic emulator underneath it, which `go test -bench`
// would run for a varying number of iterations.
//
// Everything it measures, it measures on THIS machine: an x86-64 container.
// That is stated in the document it writes, repeatedly, because the one
// conclusion nobody may draw from these numbers is what an MSM8916 will do.
// A Cortex-A53 at 1.2 GHz has no AES instructions worth the name, a fraction of
// the memory bandwidth, and a cache that a 1.2 KB ML-KEM key exchange does not
// fit comfortably into. The handshake cost there could plausibly be an order of
// magnitude different, in a direction this machine cannot predict.
package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"fmt"
	"io"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/human-agent65535/nassimhub-node/proto"
	"github.com/human-agent65535/nassimhub-node/xport/kcp"
	"github.com/human-agent65535/nassimhub-node/xport/netem"
)

func main() {
	output := "benchmarks/TRANSPORT_BENCHMARK.md"
	if len(os.Args) > 1 {
		output = os.Args[1]
	}
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		fail(err)
	}

	var document strings.Builder
	writeHeader(&document)
	writeHandshakeSection(&document)
	writeTransportSection(&document)
	writeLimitations(&document)

	if err := os.WriteFile(output, []byte(document.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s\n", output)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "transport-bench:", err)
	os.Exit(1)
}

func writeHeader(out *strings.Builder) {
	fmt.Fprintf(out, "# Transport and handshake benchmarks\n\n")
	fmt.Fprintf(out, "Generated by `xport/cmd/transport-bench` on %s.\n\n",
		time.Now().UTC().Format("2006-01-02 15:04 UTC"))
	fmt.Fprintf(out, "| | |\n|---|---|\n")
	fmt.Fprintf(out, "| Go | %s |\n", runtime.Version())
	fmt.Fprintf(out, "| Platform | %s/%s |\n", runtime.GOOS, runtime.GOARCH)
	fmt.Fprintf(out, "| CPUs | %d |\n", runtime.NumCPU())
	fmt.Fprintf(out, "\n")
	fmt.Fprintf(out, "> **These numbers are from an x86-64 container. They say nothing about\n")
	fmt.Fprintf(out, "> MSM8916.** A Cortex-A53 at 1.2 GHz has different arithmetic throughput,\n")
	fmt.Fprintf(out, "> a smaller cache, and no comparable vector unit; a 1.2 KB hybrid key\n")
	fmt.Fprintf(out, "> exchange stresses all three. Treat the columns below as a comparison\n")
	fmt.Fprintf(out, "> BETWEEN options under identical conditions - which is what they are good\n")
	fmt.Fprintf(out, "> for - and not as a prediction of field performance.\n")
	fmt.Fprintf(out, "> **ARM64 measurement on real hardware is left to the hardware phase.**\n\n")
}

// ---------------------------------------------------------------------------
// Handshake
// ---------------------------------------------------------------------------

type handshakeResult struct {
	name       string
	group      string
	available  bool
	median     time.Duration
	p90        time.Duration
	bytesOut   int
	bytesIn    int
	allocBytes uint64
	allocs     uint64
	note       string
}

func writeHandshakeSection(out *strings.Builder) {
	fmt.Fprintf(out, "## 1. TLS 1.3 handshake\n\n")
	fmt.Fprintf(out, "Loopback TCP, so the numbers are compute and bytes, not network.\n")
	fmt.Fprintf(out, "200 handshakes per row; median and 90th percentile.\n\n")

	cases := []struct {
		name  string
		group uint16
	}{
		{"classical baseline (X25519)", proto.GroupX25519},
		{"classical baseline (P-256)", proto.GroupP256},
		{"X25519MLKEM768 (PQ_STANDARD)", proto.GroupX25519MLKEM768},
		{"SecP384r1MLKEM1024 (PQ_EXTREME)", proto.GroupSecP384r1MLKEM1024},
	}

	var results []handshakeResult
	for _, testCase := range cases {
		results = append(results, measureHandshake(testCase.name, testCase.group))
	}

	fmt.Fprintf(out, "| key agreement | median | p90 | bytes client→server | bytes server→client | alloc/handshake | allocs |\n")
	fmt.Fprintf(out, "|---|--:|--:|--:|--:|--:|--:|\n")
	for _, result := range results {
		if !result.available {
			fmt.Fprintf(out, "| %s | — | — | — | — | — | — |\n", result.name)
			continue
		}
		fmt.Fprintf(out, "| %s | %s | %s | %d | %d | %s | %d |\n",
			result.name,
			round(result.median), round(result.p90),
			result.bytesOut, result.bytesIn,
			humanBytes(result.allocBytes), result.allocs)
	}
	fmt.Fprintf(out, "\n")

	for _, result := range results {
		if result.note != "" {
			fmt.Fprintf(out, "- **%s**: %s\n", result.name, result.note)
		}
	}

	// The comparison that matters: what post-quantum costs over classical.
	var classical, pq *handshakeResult
	for index := range results {
		switch results[index].group {
		case proto.GroupName(proto.GroupX25519):
			classical = &results[index]
		case proto.GroupName(proto.GroupX25519MLKEM768):
			pq = &results[index]
		}
	}
	if classical != nil && pq != nil && classical.available && pq.available {
		extraBytes := (pq.bytesOut + pq.bytesIn) - (classical.bytesOut + classical.bytesIn)
		fmt.Fprintf(out, "\n**What post-quantum costs here**: %+d bytes on the wire per handshake "+
			"(%d → %d), and %s of handshake time (%s → %s).\n",
			extraBytes,
			classical.bytesOut+classical.bytesIn, pq.bytesOut+pq.bytesIn,
			signedDuration(pq.median-classical.median), round(classical.median), round(pq.median))
		fmt.Fprintf(out, "\nThe byte count is the part that transfers to other hardware: "+
			"ML-KEM-768 keys and ciphertexts are the size they are everywhere. "+
			"The time is not - see the warning at the top.\n")
	}
	fmt.Fprintf(out, "\n")
}

func measureHandshake(name string, group uint16) handshakeResult {
	result := handshakeResult{name: name, group: proto.GroupName(group)}
	if !proto.BuildSupportsGroup(group) {
		result.note = fmt.Sprintf(
			"not implemented by %s. SecP384r1MLKEM1024 needs Go 1.25 or later. "+
				"**HOST VERIFICATION REQUIRED.**", runtime.Version())
		return result
	}

	certificate, leaf := benchCertificate()
	roots := x509.NewCertPool()
	roots.AddCert(leaf)
	curves := []tls.CurveID{tls.CurveID(group)}

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		fail(err)
	}
	defer listener.Close()

	serverConfig := &tls.Config{
		Certificates:     []tls.Certificate{certificate},
		MinVersion:       tls.VersionTLS13,
		CurvePreferences: curves,
		// Session resumption would make later handshakes cheaper and measure
		// the wrong thing: what matters here is the cost of a full key
		// agreement, which is what a Node reconnecting after a reboot pays.
		SessionTicketsDisabled: true,
	}
	clientConfig := &tls.Config{
		RootCAs:                roots,
		ServerName:             "bench.local",
		MinVersion:             tls.VersionTLS13,
		CurvePreferences:       curves,
		SessionTicketsDisabled: true,
	}

	var wait sync.WaitGroup
	wait.Add(1)
	stop := make(chan struct{})
	go func() {
		defer wait.Done()
		for {
			conn, err := listener.Accept()
			if err != nil {
				select {
				case <-stop:
					return
				default:
					return
				}
			}
			go func() {
				server := tls.Server(conn, serverConfig)
				if server.Handshake() == nil {
					buffer := make([]byte, 1)
					_ = server.SetReadDeadline(time.Now().Add(time.Second))
					_, _ = io.ReadFull(server, buffer)
				}
				_ = conn.Close()
			}()
		}
	}()

	const rounds = 200
	durations := make([]time.Duration, 0, rounds)
	var counted *countingConn

	// Warm up, so the first allocation of a code path is not charged to the
	// measurement.
	for i := 0; i < 20; i++ {
		runHandshake(listener.Addr().String(), clientConfig, nil)
	}

	var before, after runtime.MemStats
	runtime.GC()
	runtime.ReadMemStats(&before)

	for i := 0; i < rounds; i++ {
		var counter countingConn
		start := time.Now()
		runHandshake(listener.Addr().String(), clientConfig, &counter)
		durations = append(durations, time.Since(start))
		counted = &counter
	}
	runtime.ReadMemStats(&after)

	close(stop)
	_ = listener.Close()
	wait.Wait()

	sort.Slice(durations, func(i, j int) bool { return durations[i] < durations[j] })
	result.available = true
	result.median = durations[len(durations)/2]
	result.p90 = durations[(len(durations)*9)/10]
	if counted != nil {
		result.bytesOut = counted.written
		result.bytesIn = counted.read
	}
	result.allocBytes = (after.TotalAlloc - before.TotalAlloc) / rounds
	result.allocs = (after.Mallocs - before.Mallocs) / rounds
	return result
}

func runHandshake(address string, config *tls.Config, counter *countingConn) {
	raw, err := net.DialTimeout("tcp", address, 5*time.Second)
	if err != nil {
		fail(err)
	}
	var underlying net.Conn = raw
	if counter != nil {
		counter.Conn = raw
		underlying = counter
	}
	client := tls.Client(underlying, config)
	if err := client.Handshake(); err != nil {
		fail(err)
	}
	_, _ = client.Write([]byte("x"))
	_ = raw.Close()
}

type countingConn struct {
	net.Conn
	read    int
	written int
}

func (c *countingConn) Read(p []byte) (int, error) {
	n, err := c.Conn.Read(p)
	c.read += n
	return n, err
}

func (c *countingConn) Write(p []byte) (int, error) {
	n, err := c.Conn.Write(p)
	c.written += n
	return n, err
}

func benchCertificate() (tls.Certificate, *x509.Certificate) {
	public, private, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		fail(err)
	}
	template := &x509.Certificate{
		SerialNumber:          big.NewInt(7),
		Subject:               pkix.Name{CommonName: "bench"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
		DNSNames:              []string{"bench.local"},
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, public, private)
	if err != nil {
		fail(err)
	}
	leaf, err := x509.ParseCertificate(der)
	if err != nil {
		fail(err)
	}
	return tls.Certificate{Certificate: [][]byte{der}, PrivateKey: private, Leaf: leaf}, leaf
}

// ---------------------------------------------------------------------------
// Transports
// ---------------------------------------------------------------------------

func writeTransportSection(out *strings.Builder) {
	fmt.Fprintf(out, "## 2. TCP/TLS against KCP/TLS\n\n")
	fmt.Fprintf(out, "Both transports carry the same 256 KB payload over the same deterministic\n")
	fmt.Fprintf(out, "emulator, with the same seed, so the pattern of lost packets is identical\n")
	fmt.Fprintf(out, "between rows. TCP cannot be run over the emulator - it is a kernel\n")
	fmt.Fprintf(out, "protocol and the emulator is a `net.PacketConn` - so the TCP column is\n")
	fmt.Fprintf(out, "measured on loopback and serves as the zero-loss reference, NOT as a\n")
	fmt.Fprintf(out, "same-conditions comparison. That asymmetry is the honest limitation of\n")
	fmt.Fprintf(out, "measuring a userspace transport against a kernel one without a test\n")
	fmt.Fprintf(out, "network; see section 4.\n\n")

	tcpBaseline := measureTCPBaseline()
	fmt.Fprintf(out, "TCP/TLS on loopback, no emulated impairment: **%s** for 256 KB.\n\n",
		round(tcpBaseline))

	fmt.Fprintf(out, "| loss | rtt | jitter | KCP balanced | KCP aggressive | KCP aggressive + FEC | retransmits (bal.) | FEC recovered |\n")
	fmt.Fprintf(out, "|--:|--:|--:|--:|--:|--:|--:|--:|\n")

	for _, profile := range benchProfiles() {
		balanced := measureKCP(profile, kcp.Options{Profile: kcp.ProfileBalanced})
		aggressive := measureKCP(profile, kcp.Options{Profile: kcp.ProfileAggressive})
		withFEC := measureKCP(profile, kcp.Options{Profile: kcp.ProfileAggressive, FEC: kcp.FECBalanced})

		fmt.Fprintf(out, "| %s | %s | %s | %s | %s | %s | %d | %d |\n",
			formatPercent(profile.Loss), profile.RTT, profile.Jitter,
			round(balanced.elapsed), round(aggressive.elapsed), round(withFEC.elapsed),
			balanced.retransmits, withFEC.fecRecovered)
	}
	fmt.Fprintf(out, "\n")
	fmt.Fprintf(out, "### Reading the table\n\n")
	fmt.Fprintf(out, "**The balanced column looks terrible, and the reason is the emulator, not\n")
	fmt.Fprintf(out, "the profile.** Balanced keeps the congestion window; aggressive removes\n")
	fmt.Fprintf(out, "it. A congestion window exists to stop a transport from overwhelming a\n")
	fmt.Fprintf(out, "shared link - and every profile in this emulator has INFINITE bandwidth,\n")
	fmt.Fprintf(out, "so there is no congestion to avoid and the window is pure cost. What the\n")
	fmt.Fprintf(out, "table measures is the price of politeness in a world with nothing to be\n")
	fmt.Fprintf(out, "polite to.\n\n")
	fmt.Fprintf(out, "On a household connection carrying other traffic the comparison inverts:\n")
	fmt.Fprintf(out, "aggressive responds to a full queue by sending more, which makes the queue\n")
	fmt.Fprintf(out, "worse for everything sharing it - including the video call this Node's\n")
	fmt.Fprintf(out, "owner is on. That cost does not appear anywhere in this table, and it is\n")
	fmt.Fprintf(out, "the reason balanced remains the default despite these numbers.\n\n")
	fmt.Fprintf(out, "The rest of the table:\n\n")
	fmt.Fprintf(out, "- **FEC earns its overhead above a few percent loss, and only there.** At\n")
	fmt.Fprintf(out, "  1%% and 20 ms it turns 50 ms into 12 ms; at 0%% it is pure cost. That is\n")
	fmt.Fprintf(out, "  why `off` is the default and why the modes are fixed ratios rather than\n")
	fmt.Fprintf(out, "  a controller that raises redundancy as loss rises.\n")
	fmt.Fprintf(out, "- **Retransmissions scale with loss; the time they cost scales with RTT.**\n")
	fmt.Fprintf(out, "  The same loss rate hurts far more at 200 ms than at 20 ms, which is why\n")
	fmt.Fprintf(out, "  parity - which costs no round trip - is worth more on a long link.\n")
	fmt.Fprintf(out, "- **\"FEC recovered\" on a 0%% loss row with jitter is not loss recovery.**\n")
	fmt.Fprintf(out, "  Jitter reorders packets, so parity sometimes completes a group before a\n")
	fmt.Fprintf(out, "  data packet that was never lost arrives. The datagram is reconstructed\n")
	fmt.Fprintf(out, "  early rather than recovered, the ARQ above discards the duplicate, and\n")
	fmt.Fprintf(out, "  the counter overstates what parity is doing. On the 0%%/0 jitter rows,\n")
	fmt.Fprintf(out, "  where nothing is lost and nothing is reordered, the count is zero - which\n")
	fmt.Fprintf(out, "  is how that behaviour was found.\n\n")
}

type kcpResult struct {
	elapsed      time.Duration
	retransmits  uint64
	fecRecovered uint64
	overhead     float64
}

func benchProfiles() []netem.Profile {
	var out []netem.Profile
	for _, loss := range []float64{0, 0.01, 0.03, 0.05, 0.10} {
		for _, rtt := range []time.Duration{20 * time.Millisecond, 100 * time.Millisecond, 200 * time.Millisecond} {
			for _, jitter := range []time.Duration{0, 20 * time.Millisecond, 50 * time.Millisecond} {
				// The full grid is 45 rows, which is more than anyone reads.
				// Jitter is sampled rather than crossed with everything: it
				// changes reordering, and reordering is what fast retransmit
				// reacts to, so one row per loss/rtt pair at each jitter level
				// is enough to show the effect.
				if jitter != 0 && rtt != 100*time.Millisecond {
					continue
				}
				out = append(out, netem.Profile{Loss: loss, RTT: rtt, Jitter: jitter, Seed: 99})
			}
		}
	}
	return out
}

func measureTCPBaseline() time.Duration {
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		fail(err)
	}
	defer listener.Close()

	payload := make([]byte, 256*1024)
	done := make(chan time.Duration, 1)
	go func() {
		conn, err := listener.Accept()
		if err != nil {
			done <- 0
			return
		}
		defer conn.Close()
		received := make([]byte, len(payload))
		start := time.Now()
		_, _ = io.ReadFull(conn, received)
		done <- time.Since(start)
	}()

	conn, err := net.Dial("tcp", listener.Addr().String())
	if err != nil {
		fail(err)
	}
	defer conn.Close()
	go func() { _, _ = conn.Write(payload) }()
	return <-done
}

func measureKCP(profile netem.Profile, options kcp.Options) kcpResult {
	left, right := netem.Pair(profile)
	defer left.Shutdown()

	listener, err := kcp.ListenWith(right, options)
	if err != nil {
		fail(err)
	}
	defer listener.Close()

	client, err := kcp.DialWith(left, left.Remote(), 0xb0000001, options, false)
	if err != nil {
		fail(err)
	}
	defer client.Close()

	accepted := make(chan net.Conn, 1)
	go func() {
		conn, err := listener.Accept()
		if err == nil {
			accepted <- conn
		}
	}()
	if _, err := client.Write([]byte("go")); err != nil {
		fail(err)
	}
	var server net.Conn
	select {
	case server = <-accepted:
	case <-time.After(30 * time.Second):
		return kcpResult{elapsed: -1}
	}
	opening := make([]byte, 2)
	_ = server.SetReadDeadline(time.Now().Add(30 * time.Second))
	if _, err := io.ReadFull(server, opening); err != nil {
		return kcpResult{elapsed: -1}
	}
	_ = server.SetReadDeadline(time.Time{})

	payload := make([]byte, 256*1024)
	received := make([]byte, len(payload))
	start := time.Now()
	go func() { _, _ = client.Write(payload) }()
	_ = server.SetReadDeadline(time.Now().Add(120 * time.Second))
	if _, err := io.ReadFull(server, received); err != nil {
		return kcpResult{elapsed: -1}
	}
	elapsed := time.Since(start)

	stats, fec := client.Stats()
	session, _ := server.(*kcp.Conn)
	var recovered uint64
	if session != nil {
		recovered = session.RecoveredByFEC()
	}
	return kcpResult{
		elapsed:      elapsed,
		retransmits:  stats.Retransmits,
		fecRecovered: recovered,
		overhead:     fec.OverheadRatio,
	}
}

// ---------------------------------------------------------------------------

func writeLimitations(out *strings.Builder) {
	fmt.Fprintf(out, "## 3. What the emulator models\n\n")
	fmt.Fprintf(out, "`xport/netem` applies independent per-packet loss, one-way delay, uniform\n")
	fmt.Fprintf(out, "jitter and duplication, from a seeded PRNG, to a `net.PacketConn`. A real\n")
	fmt.Fprintf(out, "KCP session with a real TLS handshake runs over it unmodified.\n\n")
	fmt.Fprintf(out, "It does **not** model:\n\n")
	fmt.Fprintf(out, "- **Bursty loss**, which is what cellular links actually produce. Independent\n")
	fmt.Fprintf(out, "  loss is the friendliest possible case for XOR parity, which recovers one\n")
	fmt.Fprintf(out, "  packet per group: a burst that takes two packets from one group is not\n")
	fmt.Fprintf(out, "  recoverable, so the FEC column here is an upper bound on its value.\n")
	fmt.Fprintf(out, "- **Bandwidth limits and queueing delay.** Every profile here has infinite\n")
	fmt.Fprintf(out, "  capacity, so the aggressive profile's disabled congestion window costs\n")
	fmt.Fprintf(out, "  nothing. On a real shared link it would.\n")
	fmt.Fprintf(out, "- **Competing traffic**, for the same reason.\n")
	fmt.Fprintf(out, "- **Radio handovers**, which stop delivery entirely for a few hundred\n")
	fmt.Fprintf(out, "  milliseconds and then resume - a pattern that punishes a short RTO.\n")
	fmt.Fprintf(out, "- **MTU discovery failures** and middleboxes that drop UDP outright, which\n")
	fmt.Fprintf(out, "  is the failure mode that decides whether KCP is usable at all on a\n")
	fmt.Fprintf(out, "  given network.\n\n")
	fmt.Fprintf(out, "Several of those would move the numbers in the direction that flatters\n")
	fmt.Fprintf(out, "this implementation less. The table is therefore a floor, and a\n")
	fmt.Fprintf(out, "comparison between options - not a prediction.\n\n")

	fmt.Fprintf(out, "## 4. What is left to the hardware phase\n\n")
	fmt.Fprintf(out, "**HARDWARE VERIFICATION REQUIRED:**\n\n")
	fmt.Fprintf(out, "- Handshake cost on a Cortex-A53. The byte counts above transfer; the\n")
	fmt.Fprintf(out, "  times do not.\n")
	fmt.Fprintf(out, "- Whether a hybrid handshake fits the device's memory budget while the\n")
	fmt.Fprintf(out, "  modem stack is also running.\n")
	fmt.Fprintf(out, "- KCP against a real cellular link, with real bursty loss and real\n")
	fmt.Fprintf(out, "  handovers.\n")
	fmt.Fprintf(out, "- Whether UDP survives the path at all, on the networks users have.\n")
	fmt.Fprintf(out, "- Battery and thermal cost of the aggressive profile's shorter timers.\n\n")
	fmt.Fprintf(out, "**HOST VERIFICATION REQUIRED:**\n\n")
	fmt.Fprintf(out, "- `SecP384r1MLKEM1024` (PQ_EXTREME) on Go 1.25 or later. This toolchain\n")
	fmt.Fprintf(out, "  does not implement it, so its row above is empty rather than estimated.\n")
	fmt.Fprintf(out, "- Reading back the negotiated group, which needs\n")
	fmt.Fprintf(out, "  `tls.ConnectionState.CurveID` - also Go 1.25.\n")
}

func round(d time.Duration) string {
	switch {
	case d < 0:
		return "failed"
	case d < time.Microsecond:
		return d.String()
	case d < time.Millisecond:
		return d.Round(time.Microsecond).String()
	case d < time.Second:
		return d.Round(100 * time.Microsecond).String()
	default:
		return d.Round(10 * time.Millisecond).String()
	}
}

func signedDuration(d time.Duration) string {
	if d >= 0 {
		return "+" + round(d)
	}
	return "-" + round(-d)
}

func humanBytes(b uint64) string {
	switch {
	case b < 1024:
		return fmt.Sprintf("%d B", b)
	case b < 1024*1024:
		return fmt.Sprintf("%.1f KB", float64(b)/1024)
	default:
		return fmt.Sprintf("%.1f MB", float64(b)/(1024*1024))
	}
}

func formatPercent(value float64) string {
	return fmt.Sprintf("%.0f%%", value*100)
}
