[Service]
ProtectProc=default
PrivateDevices=no
DevicePolicy=closed
DeviceAllow=char-alsa rw
SupplementaryGroups=audio
ExecStart=
ExecStart=/usr/bin/nassimhub-agent -config /etc/nassimhub/agent.conf -voice-media
ExecStartPre=
ExecStartPre=/usr/bin/nassimhub-agent -config /etc/nassimhub/agent.conf -voice-media -check-config
ExecStopPost=+/usr/bin/mmcli -m any --voice-hangup-all
